import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@scholaid/ui/styles.css";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { LenisProvider } from "@/providers/lenis";
import { ThemeProvider } from "@/providers/theme";
import {
  apfelGrotezk,
  apfelGrotezkFett,
  apfelGrotezkMittel,
  momoTrustDisplay,
  patuaOne,
  protestStrike,
  sketchup,
} from "@/lib/fonts";
/* import { GooeyToaster } from "@/providers/toaster"; */

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${apfelGrotezk.variable} ${apfelGrotezkFett.variable} ${apfelGrotezkMittel.variable} ${momoTrustDisplay.variable} ${patuaOne.variable} ${protestStrike.variable} ${sketchup.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LenisProvider>{children}</LenisProvider>
          {/* <GooeyToaster /> */}
        </ThemeProvider>
        {process.env.NODE_ENV === "production" && <Analytics />}
      </body>
    </html>
  );
}
