import type { Metadata } from "next";
import { Geist, Noto_Sans, Instrument_Sans } from "next/font/google";
import "@scholaid/ui/styles.css";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { LenisProvider } from "@/providers/lenis";
import { ThemeProvider } from "@/providers/theme";
import {
  apfelGrotezk,
  apfelGrotezkFett,
  apfelGrotezkMittel,
  momoTrustDisplay,
  patuaOne,
  protestStrike,
  sketchup,
} from "@/lib/fonts";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

const instrumentSansHeading = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" });

/* import { GooeyToaster } from "@/providers/toaster"; */

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "font-sans",
        notoSans.variable,
        instrumentSansHeading.variable,
      )}
    >
      <body
        className={` ${apfelGrotezk.variable} ${apfelGrotezkFett.variable} ${apfelGrotezkMittel.variable} ${momoTrustDisplay.variable} ${patuaOne.variable} ${protestStrike.variable} ${sketchup.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <LenisProvider>{children}</LenisProvider>
          </TooltipProvider>
          {/* <GooeyToaster /> */}
        </ThemeProvider>
        {process.env.NODE_ENV === "production" && <Analytics />}
      </body>
    </html>
  );
}
